### ISSUE TITLE
New links to GR4J references in README

### ISSUE THREAD

**Issue by odelaigue** [amacd31/gr4j#1]
For your information, the Excel sheet is now available at the following address (the old link is no longer valid), on a GitLab repository.
https://gitlab.irstea.fr/HYCAR-Hydro/ExcelGR/raw/master/GR4J/GR4J_EN.xlsx

The address of the page explaining how the model works is now the following:
https://webgr.inrae.fr/en/models/daily-hydrological-model-gr4j/description-of-the-gr4j-model/

For information, INRAE is the result of the merger of two organizations (IRSTEA and INRA). This is why there is a new URL for webGR website.

**Comment by amacd31** [comment]
Thanks @odelaigue, appreciate you pointing out the correct links to those resources so I could easily update the README.

**Comment by Paulg1019** [comment]
pls good evening , i am in need of the GR2M excel for english version
